### PR TITLE
Voltron

### PR DESCRIPTION
**Pull request by racheldonovan**
Melanie won't just be in Voltron standup on Mondays, so adding her as a member of the team

### CODE REVIEW

**Comment by fromonesrc** [comment]
:thumbsup:

**Comment by plukevdh** [comment]
Btw, you might need to add her in slack via the commands, since the seed data is just used first time we add this behavior or if redis gets reset.

**Comment by racheldonovan** [comment]
yup did that :)

**Comment by plukevdh** [comment]
:+1:

**Pull request merged**
