### PR TITLE
Use RedisBrain to allow teams to be configured via the chat client

### PR DESCRIPTION
**Pull request by plukevdh**
adds:

- `standup add <user> to <team>`
- `standup remove <user> from <team>`

### CODE REVIEW

**Comment by plukevdh** [comment]
Note: Seeds only get used first time (so that our existing teams get ported in). We don't need to keep this up to date and should probably drop somewhere down the line.

**Comment by fromonesrc** [comment]
:tada: This is awesome! Were you thinking of adding a way to add teams?

**Comment by plukevdh** [comment]
@fromonesrc all you gotta do is start adding people to a team `standup add Luke to Mint`. It creates the team on the fly.

**Comment by fromonesrc** [comment]
:sparkles:

**Comment by fromonesrc** [comment]
Latest commit seems to have broken the things (was working great prior)

**Comment by plukevdh** [comment]
Details?

**Comment by fromonesrc** [comment]
A flushdb fixored it. 

Error was:

```
botzo> botzo standup ops
botzo> Good day, Ops team!
botzo> [Thu Apr 23 2015 16:51:10 GMT-0400 (EDT)] ERROR Unable to call the listener: TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
  at Team._shuffle (/Users/fromonesrc/src/botzo/scripts/standup.coffee:39:5, <js>:46:19)
  at Team.standupOrder (/Users/fromonesrc/src/botzo/scripts/standup.coffee:36:5, <js>:41:26)
  at TextListener.callback (/Users/fromonesrc/src/botzo/scripts/standup.coffee:78:15, <js>:109:52)
  at TextListener.Listener.call (/Users/fromonesrc/src/botzo/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
  at Robot.receive (/Users/fromonesrc/src/botzo/node_modules/hubot/src/robot.coffee:163:9, <js>:112:33)
  at Shell.Adapter.receive (/Users/fromonesrc/src/botzo/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at Interface.<anonymous> (/Users/fromonesrc/src/botzo/node_modules/hubot/src/adapters/shell.coffee:41:7, <js>:85:22)
  at Interface.emit (events.js:95:17)
  at Interface._onLine (readline.js:202:10)
  at Interface._line (readline.js:531:8)
  at Interface._ttyWrite (readline.js:760:14)
  at ReadStream.onkeypress (readline.js:99:10)
  at ReadStream.emit (events.js:98:17)
  at emitKey (readline.js:1095:12)
  at ReadStream.onData (readline.js:840:14)
  at ReadStream.emit (events.js:95:17)
  at ReadStream.<anonymous> (_stream_readable.js:764:14)
  at ReadStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at emitReadable (_stream_readable.js:422:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at ReadStream.Readable.push (_stream_readable.js:127:10)
  at TTY.onread (net.js:528:21)
botzo> botzo standup add foo to bar
botzo> [Thu Apr 23 2015 16:51:21 GMT-0400 (EDT)] ERROR Unable to call the listener: TypeError: Cannot call method 'push' of undefined
TypeError: Cannot call method 'push' of undefined
  at Team.addMember (/Users/fromonesrc/src/botzo/scripts/standup.coffee:27:5, <js>:29:27)
  at TextListener.callback (/Users/fromonesrc/src/botzo/scripts/standup.coffee:85:5, <js>:115:12)
  at TextListener.Listener.call (/Users/fromonesrc/src/botzo/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
  at Robot.receive (/Users/fromonesrc/src/botzo/node_modules/hubot/src/robot.coffee:163:9, <js>:112:33)
  at Shell.Adapter.receive (/Users/fromonesrc/src/botzo/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at Interface.<anonymous> (/Users/fromonesrc/src/botzo/node_modules/hubot/src/adapters/shell.coffee:41:7, <js>:85:22)
  at Interface.emit (events.js:95:17)
  at Interface._onLine (readline.js:202:10)
  at Interface._line (readline.js:531:8)
  at Interface._ttyWrite (readline.js:760:14)
  at ReadStream.onkeypress (readline.js:99:10)
  at ReadStream.emit (events.js:98:17)
  at emitKey (readline.js:1095:12)
  at ReadStream.onData (readline.js:840:14)
  at ReadStream.emit (events.js:95:17)
  at ReadStream.<anonymous> (_stream_readable.js:764:14)
  at ReadStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at emitReadable (_stream_readable.js:422:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at ReadStream.Readable.push (_stream_readable.js:127:10)
  at TTY.onread (net.js:528:21)
```

Weird. Any ideas? I don't want to have to flush botzo's redis brain.

**Comment by plukevdh** [comment]
Can you pull and try again @fromonesrc?

**Comment by plukevdh** [comment]
Also, do a `HUBOT_LOG_LEVEL=debug ./bin/hubot -n botzo` and give me any additional output about the Redis data for the standup teams data.

**Comment by plukevdh** [comment]
should look something like:
```
[Fri Apr 24 2015 10:09:52 GMT-0400 (EDT)] DEBUG Loaded Standup Team Data {
  "voltron": {
    "members": [
      "Brian",
      "Rachel",
      "Kevin",
      "Eric",
      "Julie",
      "Matt",
      "Dave",
      "Lindsey",
      "Darren",
      "Sherry",
      "Katrina",
      "Gabe"
    ]
  },
  "ops": {
    "members": [
      "ocho",
      "spurr",
      "megatron"
    ]
  },
  "mint": {
    "members": [
      "Luke",
      "Thom",
      "Sarah"
    ]
  }
}
```

**Comment by fromonesrc** [comment]
Working great, I'm not seeing any problems since I flushed redis last night and not seeing any problems in this new commit.

**Comment by plukevdh** [comment]
:+1: :shipit:

**Comment by fromonesrc** [comment]
```
[Fri Apr 24 2015 10:23:40 GMT-0400 (EDT)] DEBUG Loaded Standup Team Data {
  "voltron": {
    "members": [
      "Julie",
      "Gabe",
      "Darren",
      "Dave",
      "Rachel",
      "Eric",
      "Sherry",
      "Kevin",
      "Katrina",
      "Lindsey",
      "Matt",
      "Brian"
    ]
  },
  "ops": {
    "members": [
      "megatron",
      "ocho",
      "spurr"
    ]
  },
  "bar": {
    "members": [
      "foo"
    ]
  }
}
```

**Pull request merged**
