### PR TITLE
Because ain't nobody got time for `man`

### PR DESCRIPTION
**Pull request by fromonesrc**
```
botzo> botzo explainshell tar xvzf ball.tar.gz
botzo> http://explainshell.com/explain?cmd=tar+xvzf+ball.tar.gz
```

tumblr_nfqat6ihdq1qd5mq1o1_500

### CODE REVIEW

**Comment by plukevdh** [comment]
Love explainshell

**Comment by plukevdh** [comment]
image

**Comment by mikeolivieri** [comment]
Is there a way to make botzo only show the person who asks for this info the result?

**Comment by plukevdh** [comment]
I believe so. Requires specific syntax from the slack API

**Comment by mikeolivieri** [comment]
There's some concern about the level of noise in many of the rooms. Just got me thinking about things like this.

**Comment by plukevdh** [comment]
https://api.slack.com/methods/im.open

**Comment by fromonesrc** [comment]
Oh that gives me a great big sad.

**Comment by mikeolivieri** [comment]
We don't need to do it. I was just curious. 

I do kind of get the noise thing though.

**Pull request merged**
