### PR TITLE
weather forecasting for botzo

### PR DESCRIPTION
**Pull request by plukevdh**
`botzo weather for Bluffton, SC`

```
botzo> Currently it is 55.1°F (feels like 55.1°F).
Wind is 5.03mph out of undefined with a 0% chance of rain.
Partly cloudy for the hour.
Partly cloudy throughout the day.
Light rain on Sunday and Monday, with temperatures falling to 35°F on Thursday.
```

requires an API key from developer.forecast.io

### CODE REVIEW

**Comment by mikeolivieri** [comment]
Nice! Ugh, it is going to snow tomorrow :( 
rs8qagrw0xbok_vskuh1948ot8tf7jeeusb6t3pgyrk

:shipit:

**Comment by plukevdh** [comment]
Did it end up snowing @mikeolivieri?

**Comment by plukevdh** [comment]
@donbecker / @fromonesrc can I get a `FORECAST_IO_API_KEY` set for botzo? I can give you my key unless you want to create one specific for Articulate.

**Comment by fromonesrc** [comment]
API key added :+1:

**Pull request merged**
