### PR TITLE
adds screenr reboot script to hubot

### PR DESCRIPTION
**Pull request by d4v3y0rk**
giphy 1

@articulate/web-ops 
should work just fine...

### CODE REVIEW

**Comment by d4v3y0rk** [comment]
@articulate/web-ops

**Comment by plukevdh** [comment]
I might wanna ensure only certain users can do this. I can imagine someone just pushing this button for funz

**Comment by d4v3y0rk** [comment]
I am not sure how your rolez are setup with hubot, as there are different ways to do that...

**Comment by fromonesrc** [comment]
We can probably get away without roles on that. This is a huge help Dave! Gets us through another 2 months before the paid service goes away.

**Pull request merged**
