### PR TITLE
botzo standup voltron had a case of the Mondays

### PR DESCRIPTION
**Pull request by fromonesrc**

### CODE REVIEW

**Comment by plukevdh** [comment]
Good enough for now. Hoping to make this kind of behavior dynamic as well.

**Comment by fromonesrc** [comment]
@racheldonovan is gonna :eyes: before :ship:

**Comment by fromonesrc** [comment]
Fixed, good catch @plukevdh

**Comment by racheldonovan** [comment]
I'm seeing strange issues with both the push method and the addMember approach (basically she gets added over and over and never removed), I'm going to take a pass at a fix

**Comment by racheldonovan** [comment]
Just pushed a fix, let me know what you think.

**Comment by fromonesrc** [comment]
LGTM :thumbsup:

**Comment by plukevdh** [comment]
I can replicate here: 

https://jsfiddle.net/plukevdh/tjtk10L7/

and can fix using a `_.clone` of members. :scumbag: pass by ref

http://jsfiddle.net/plukevdh/tjtk10L7/1/

**Comment by racheldonovan** [comment]
nice fix, looks good to :ship: to me!

**Pull request merged**
