### PR TITLE
Multiple team standups

### PR DESCRIPTION
**Pull request by fromonesrc**
```
botzo> botzo standup voltron
botzo> Good day, Voltron team!
botzo> Standup order is: Kevin,Brian,Matt,Eric,Darren,Lindsey,Dave,Gabe,Rachel,Julie,Katrina,Sherry
botzo> botzo standup ops
botzo> Good day, Ops team!
botzo> Standup order is: megatron,ocho,spurr
botzo> botzo organize standup for voltron
botzo> Good day, Voltron team!
botzo> Standup order is: Brian,Kevin,Dave,Darren,Sherry,Katrina,Julie,Rachel,Matt,Gabe,Eric,Lindsey
```

@racheldonovan I'm piggypacking on the awesome standup script you have for voltron, made a few changes to make it generic for other teams to use. Do you dig?

@articulate/web-ops

### CODE REVIEW

**Comment by racheldonovan** [comment]
I :heart: , :shipit:

**Comment by plukevdh** [comment]
Would be awesome if we could configure these on the fly rather than hardcoded...

**Comment by fromonesrc** [comment]
I'd love that!

**Comment by plukevdh** [comment]
Investigating. Will PR.

**Pull request merged**
