### PR TITLE
need to bump the time version

### PR DESCRIPTION
**Pull request by d4v3y0rk**
- this version of the time npm package is not compatible with newer versions of
  node

### CODE REVIEW

**Comment by plukevdh** [comment]
do we want to bump node version here as well or is this :ship:worthy?

**Comment by plukevdh** [comment]
Can otherwise confirm this fixes :+1:

**Comment by d4v3y0rk** [comment]
have you confirmed that this version of time works with the node version Heroku will run Botzo with?

**Comment by d4v3y0rk** [comment]
@plukevdh I think we need to confirm this works with the node version in the .node-version file or bump it.

**Comment by plukevdh** [comment]
Can we get some action on this?

**Comment by fromonesrc** [comment]
@plukevdh feel free to action away

**Comment by plukevdh** [comment]
@fromonesrc dunno if we have a way to check compat with wherever this is being hosted from? Was unsure where @d4v3y0rk was leaving this...

**Pull request merged**
